### ISSUE TITLE
Exception when clicking cancel in file dialog

### ISSUE THREAD

**Issue by barneywilliams** [AddJam/ember-image-drop#2]
If I select an image file in the file dialog, and then click `Cancel`, I get the following error in the console:

`Uncaught TypeError: Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'.`

I am testing in OSX El Capitan, but guessing it isn't platform-specific.

**Comment by barneywilliams** [comment]
Added fix in pull request #3

**Comment by chrissloey** [comment]
Thanks, closing now that it's merged. Will release a new version now.
