### ISSUE TITLE
Redundantly setting base64 image

### ISSUE THREAD

**Issue by abulrim** [AddJam/ember-image-drop#6]
Why is `convertImgToBase64URL` used [here](https://github.com/AddJam/ember-image-drop/blob/master/addon/components/image-drop.js#L72) while `FileReader` already sets the base64 image [here](https://github.com/AddJam/ember-image-drop/blob/master/addon/components/image-drop.js#L49). Aren't these two function basically doing the same thing?

**Comment by chrissloey** [comment]
First one handles a URL being dropped, second handles a file being dropped. URL being dropped could happen when someone drags an image from another browser window. Code could definitely be improved though.

**Comment by chrissloey** [comment]
Closing this for now, open to PRs to tidy it up a bit.

**Comment by abulrim** [comment]
Great, I'll work on it when I have some free time :smile:
